package vannon.syx.economy.core;

/**
 * Build identity anchor — unique per compilation.
 *
 * <p>During Maven builds, this file is regenerated by
 * {@code tools/generate-build-stamp.sh} in the {@code generate-sources}
 * phase with the real git hash, timestamp, and dirty flag.
 *
 * <p>When working in an IDE without Maven, this stub provides a
 * fallback identity ({@code DEV}) so the code compiles.
 * Run {@code mvn generate-sources} to refresh.</p>
 *
 * <p>Commit this stub once. Maven overwrites it on every build.
 * Do not stage the regenerated version — treat it like a build artifact.</p>
 */
public final class BuildStamp {
    public static final String VERSION    = "0.0.0";
    public static final String GIT_HASH   = "DEV";
    public static final String BUILD_TIME = "IDE";
    public static final String DIRTY      = "";
    public static final String FULL_ID    = "vDEV (IDE)";
    private BuildStamp() {}
}
