#!/usr/bin/env bash
# Generates BuildStamp.java with unique per-compile identity:
#   - pom.xml version
#   - short git commit hash
#   - ISO-8601 build timestamp
#   - dirty-flag if working tree has uncommitted changes
#
# Called by Maven antrun during generate-sources phase.
# Output: target/generated-sources/vannon/syx/economy/core/BuildStamp.java

set -euo pipefail

OUTDIR="${1:?usage: $0 <output-dir>}"
VERSION="${2:?usage: $0 <output-dir> <version>}"
mkdir -p "$OUTDIR"

GIT_HASH="unknown"
if command -v git &>/dev/null && git rev-parse --git-dir &>/dev/null 2>&1; then
  GIT_HASH="$(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
fi

BUILD_TIME="$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date +"%Y-%m-%dT%H:%M:%SZ")"

DIRTY=""
if command -v git &>/dev/null && git rev-parse --git-dir &>/dev/null 2>&1; then
  if ! git diff --quiet --exit-code 2>/dev/null || \
     ! git diff --cached --quiet --exit-code 2>/dev/null; then
    DIRTY="-DIRTY"
  fi
fi

FULL_ID="v${VERSION}-${GIT_HASH}${DIRTY}"

cat > "$OUTDIR/BuildStamp.java" << EOF
package vannon.syx.economy.core;

/** Auto-generated by tools/generate-build-stamp.sh during Maven generate-sources.
 *  Unique per compilation. Never commit this file — it is regenerated every build. */
public final class BuildStamp {
    public static final String VERSION   = "${VERSION}";
    public static final String GIT_HASH  = "${GIT_HASH}";
    public static final String BUILD_TIME = "${BUILD_TIME}";
    public static final String DIRTY     = "${DIRTY}";
    public static final String FULL_ID   = "${FULL_ID}";
    private BuildStamp() {}
}
EOF

echo "[generate-build-stamp] ${FULL_ID}"
